# @package _global_

# Step decay learning rate schedule
training:
  lr_schedule_type: "plateau"
  lr_schedule_config:
    mode: "max"
    # factor: 0.1
    # patience: 10
    # threshold: 1e-4
    # threshold_mode: "rel"
    # cooldown: 0
    # min_lr: 0
    # eps: 1e-8
    # verbose: false

    # train-totloss
    monitor: "val-Abs Cosine Sim v1"
    frequency: 1