name: gad
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python==3.11
  - pytorch::pytorch==2.5.1
  - pytorch::pytorch-cuda=12.1
  # - matplotlib  # we cannot depend on matplotlib explicitly, it works implicitly
  - jupyter
  - pip
  - ase==3.25.0
  - numpy>=1.26.0,<2.0.0
  - scipy
  - scikit-learn
  - tqdm
  # - rdkit>=2024.3.6  # this version (potentially or above) is required!! (earlier, maybe all) 2023 versions do not work
  - conda-forge::rdkit=2024
  - openbabel=3.1.1
  - pyyaml
  - seaborn
  - dxtb
  - mctc-lib
  - torchmetrics
  - pip:
    - joblib
    - submitit
    - pre-commit
    - black==22.6.0
    - kagglehub>=0.3.12
    - usort==1.0.4
    - ufmt==2.3.0
    - flake8==7.0.0
    - hydra-core
    - hydra-submitit-launcher
    - rmsd
    - pytorch_warmup
    - e3nn==0.5.1
    - fairchem-core==1.10.0
    - huggingface_hub>=0.27.1
    - cuequivariance-ops-torch-cu12==0.5.0
    - cuequivariance-torch==0.5.0
    - networkx==3.4.2
    - wandb==0.19.11
    - pydantic==2.11.4
    - opt-einsum-fx==0.1.4
    - triton==2.2.0
    - lmdb==1.5.1
    - py3Dmol==2.5.0
    - h5py>=3.10.0
    - progressbar==2.5
    # Editable install with no version control (mace-torch==0.3.14)
    - pytorch-lightning==2.5.1.post0
    - -e .
    # from here below, we use find-links
    - --find-links https://data.pyg.org/whl/torch-2.5.1+cu121.html
    - torch_cluster==1.6.3+pt25cu121
    - torch_geometric==2.6.1
    - pyg-lib==0.4.0+pt25cu121
    - torch_scatter==2.1.2+pt25cu121
    - torch_sparse==0.6.18+pt25cu121
    - torch_spline_conv==1.2.2+pt25cu121
