# @package _global_

potential_module_class: "EigenPotentialModule"

training:
  # Loss type
  loss_type: "mse"
  # Sign-invariant loss for eigenvectors: "cosine", "min_l2", "min_l1", "l1", "l2"
  loss_type_vec: "cosine"  

  # Loss weights
  weight_eigval1: 1.0
  weight_eigval2: 1.0
  weight_eigvec1: 1.0
  weight_eigvec2: 1.0
  
model:
  # Added for eigenvalue/eigenvector prediction
  do_eigvec_1: true
  do_eigvec_2: false  
  do_eigval_1: true
  do_eigval_2: true

  do_hessian: false
  hessian_alpha_drop: 0.0