# @package _global_

potential_module_class: "HessianPotentialModule"

model:
  # Added for eigenvalue/eigenvector prediction
  do_eigvec_1: false
  do_eigvec_2: false  
  do_eigval_1: false
  do_eigval_2: false

  do_hessian: true
  hessian_alpha_drop: 0.0
  num_layers_hessian: 0