# @package _global_

model:
  alpha_drop:               0.0         # [0.0, 0.1]
  drop_path_rate:           0.0         # [0.0, 0.05]
  proj_drop:                0.0

# Step decay learning rate schedule
training:
  
  mask_hessian: false
  eigen_loss:
    loss_name: "eigenspectrum"
    loss_type: "eigen" # eigen=luca or wa
    k: 8
    alpha: 1.0
    dof_filter_fn: null
