# @package _global_

model:
  alpha_drop:               0.0         # [0.0, 0.1]
  drop_path_rate:           0.0         # [0.0, 0.05]
  proj_drop:                0.0


training:
  
  hessian_loss_weight: 0.0

  mask_hessian: false
  eigen_loss:
    loss_name: "eigenspectrum"
    loss_type: "eigen" # eigen or wa
    k: [null, 8]
    alpha: [0.1, 1.0]
    dof_filter_fn: null
